// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/shared/proto/gonduit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostInfo      *HostInfo              `protobuf:"bytes,1,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *HelloResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type HostInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Ip             string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Port           string                 `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	NetworkAdapter string                 `protobuf:"bytes,6,opt,name=network_adapter,json=networkAdapter,proto3" json:"network_adapter,omitempty"`
	OsInfo         *OSInfo                `protobuf:"bytes,7,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{2}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HostInfo) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *HostInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *HostInfo) GetNetworkAdapter() string {
	if x != nil {
		return x.NetworkAdapter
	}
	return ""
}

func (x *HostInfo) GetOsInfo() *OSInfo {
	if x != nil {
		return x.OsInfo
	}
	return nil
}

type OSInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        string                 `protobuf:"bytes,1,opt,name=Family,proto3" json:"Family,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Build         string                 `protobuf:"bytes,4,opt,name=Build,proto3" json:"Build,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=Arch,proto3" json:"Arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{3}
}

func (x *OSInfo) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *OSInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *OSInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ShellClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*ShellClientMessage_ListTypes
	//	*ShellClientMessage_ListSessions
	//	*ShellClientMessage_Create
	//	*ShellClientMessage_Kill
	//	*ShellClientMessage_Stdin
	//	*ShellClientMessage_Resize
	//	*ShellClientMessage_Attach
	//	*ShellClientMessage_Detach
	//	*ShellClientMessage_Dump
	Message       isShellClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellClientMessage) Reset() {
	*x = ShellClientMessage{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellClientMessage) ProtoMessage() {}

func (x *ShellClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellClientMessage.ProtoReflect.Descriptor instead.
func (*ShellClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{4}
}

func (x *ShellClientMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShellClientMessage) GetMessage() isShellClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ShellClientMessage) GetListTypes() *ListShellTypes {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_ListTypes); ok {
			return x.ListTypes
		}
	}
	return nil
}

func (x *ShellClientMessage) GetListSessions() *ListShellSessions {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_ListSessions); ok {
			return x.ListSessions
		}
	}
	return nil
}

func (x *ShellClientMessage) GetCreate() *ShellCreate {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *ShellClientMessage) GetKill() *ShellKill {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

func (x *ShellClientMessage) GetStdin() *ShellStdin {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ShellClientMessage) GetResize() *ShellResize {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ShellClientMessage) GetAttach() *ShellAttach {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ShellClientMessage) GetDetach() *ShellDetach {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

func (x *ShellClientMessage) GetDump() *ShellDump {
	if x != nil {
		if x, ok := x.Message.(*ShellClientMessage_Dump); ok {
			return x.Dump
		}
	}
	return nil
}

type isShellClientMessage_Message interface {
	isShellClientMessage_Message()
}

type ShellClientMessage_ListTypes struct {
	ListTypes *ListShellTypes `protobuf:"bytes,2,opt,name=list_types,json=listTypes,proto3,oneof"`
}

type ShellClientMessage_ListSessions struct {
	ListSessions *ListShellSessions `protobuf:"bytes,3,opt,name=list_sessions,json=listSessions,proto3,oneof"`
}

type ShellClientMessage_Create struct {
	Create *ShellCreate `protobuf:"bytes,4,opt,name=create,proto3,oneof"`
}

type ShellClientMessage_Kill struct {
	Kill *ShellKill `protobuf:"bytes,5,opt,name=kill,proto3,oneof"`
}

type ShellClientMessage_Stdin struct {
	Stdin *ShellStdin `protobuf:"bytes,6,opt,name=stdin,proto3,oneof"`
}

type ShellClientMessage_Resize struct {
	Resize *ShellResize `protobuf:"bytes,7,opt,name=resize,proto3,oneof"`
}

type ShellClientMessage_Attach struct {
	Attach *ShellAttach `protobuf:"bytes,8,opt,name=attach,proto3,oneof"`
}

type ShellClientMessage_Detach struct {
	Detach *ShellDetach `protobuf:"bytes,9,opt,name=detach,proto3,oneof"`
}

type ShellClientMessage_Dump struct {
	Dump *ShellDump `protobuf:"bytes,10,opt,name=dump,proto3,oneof"`
}

func (*ShellClientMessage_ListTypes) isShellClientMessage_Message() {}

func (*ShellClientMessage_ListSessions) isShellClientMessage_Message() {}

func (*ShellClientMessage_Create) isShellClientMessage_Message() {}

func (*ShellClientMessage_Kill) isShellClientMessage_Message() {}

func (*ShellClientMessage_Stdin) isShellClientMessage_Message() {}

func (*ShellClientMessage_Resize) isShellClientMessage_Message() {}

func (*ShellClientMessage_Attach) isShellClientMessage_Message() {}

func (*ShellClientMessage_Detach) isShellClientMessage_Message() {}

func (*ShellClientMessage_Dump) isShellClientMessage_Message() {}

type ShellServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*ShellServerMessage_Ok
	//	*ShellServerMessage_Stdout
	//	*ShellServerMessage_Error
	//	*ShellServerMessage_Exited
	//	*ShellServerMessage_Types
	//	*ShellServerMessage_Sessions
	//	*ShellServerMessage_Attached
	//	*ShellServerMessage_Dump
	Message       isShellServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellServerMessage) Reset() {
	*x = ShellServerMessage{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellServerMessage) ProtoMessage() {}

func (x *ShellServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellServerMessage.ProtoReflect.Descriptor instead.
func (*ShellServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{5}
}

func (x *ShellServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShellServerMessage) GetMessage() isShellServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ShellServerMessage) GetOk() *ShellOk {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ShellServerMessage) GetStdout() *ShellStdout {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ShellServerMessage) GetError() *ShellError {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ShellServerMessage) GetExited() *ShellExited {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *ShellServerMessage) GetTypes() *ShellTypes {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Types); ok {
			return x.Types
		}
	}
	return nil
}

func (x *ShellServerMessage) GetSessions() *ShellSessions {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Sessions); ok {
			return x.Sessions
		}
	}
	return nil
}

func (x *ShellServerMessage) GetAttached() *ShellAttached {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Attached); ok {
			return x.Attached
		}
	}
	return nil
}

func (x *ShellServerMessage) GetDump() *ShellDumpData {
	if x != nil {
		if x, ok := x.Message.(*ShellServerMessage_Dump); ok {
			return x.Dump
		}
	}
	return nil
}

type isShellServerMessage_Message interface {
	isShellServerMessage_Message()
}

type ShellServerMessage_Ok struct {
	Ok *ShellOk `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

type ShellServerMessage_Stdout struct {
	Stdout *ShellStdout `protobuf:"bytes,3,opt,name=stdout,proto3,oneof"`
}

type ShellServerMessage_Error struct {
	Error *ShellError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type ShellServerMessage_Exited struct {
	Exited *ShellExited `protobuf:"bytes,5,opt,name=exited,proto3,oneof"`
}

type ShellServerMessage_Types struct {
	Types *ShellTypes `protobuf:"bytes,6,opt,name=types,proto3,oneof"`
}

type ShellServerMessage_Sessions struct {
	Sessions *ShellSessions `protobuf:"bytes,7,opt,name=sessions,proto3,oneof"`
}

type ShellServerMessage_Attached struct {
	Attached *ShellAttached `protobuf:"bytes,8,opt,name=attached,proto3,oneof"`
}

type ShellServerMessage_Dump struct {
	Dump *ShellDumpData `protobuf:"bytes,9,opt,name=dump,proto3,oneof"`
}

func (*ShellServerMessage_Ok) isShellServerMessage_Message() {}

func (*ShellServerMessage_Stdout) isShellServerMessage_Message() {}

func (*ShellServerMessage_Error) isShellServerMessage_Message() {}

func (*ShellServerMessage_Exited) isShellServerMessage_Message() {}

func (*ShellServerMessage_Types) isShellServerMessage_Message() {}

func (*ShellServerMessage_Sessions) isShellServerMessage_Message() {}

func (*ShellServerMessage_Attached) isShellServerMessage_Message() {}

func (*ShellServerMessage_Dump) isShellServerMessage_Message() {}

type ShellOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellOk) Reset() {
	*x = ShellOk{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOk) ProtoMessage() {}

func (x *ShellOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOk.ProtoReflect.Descriptor instead.
func (*ShellOk) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{6}
}

func (x *ShellOk) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

type ShellExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellExited) Reset() {
	*x = ShellExited{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExited) ProtoMessage() {}

func (x *ShellExited) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExited.ProtoReflect.Descriptor instead.
func (*ShellExited) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{7}
}

func (x *ShellExited) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShellExited) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShellError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellError) Reset() {
	*x = ShellError{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellError) ProtoMessage() {}

func (x *ShellError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellError.ProtoReflect.Descriptor instead.
func (*ShellError) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{8}
}

func (x *ShellError) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShellStdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStdin) Reset() {
	*x = ShellStdin{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStdin) ProtoMessage() {}

func (x *ShellStdin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStdin.ProtoReflect.Descriptor instead.
func (*ShellStdin) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{9}
}

func (x *ShellStdin) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellStdin) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellAttached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellAttached) Reset() {
	*x = ShellAttached{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellAttached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellAttached) ProtoMessage() {}

func (x *ShellAttached) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellAttached.ProtoReflect.Descriptor instead.
func (*ShellAttached) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{10}
}

func (x *ShellAttached) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellAttached) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellStdout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStdout) Reset() {
	*x = ShellStdout{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStdout) ProtoMessage() {}

func (x *ShellStdout) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStdout.ProtoReflect.Descriptor instead.
func (*ShellStdout) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{11}
}

func (x *ShellStdout) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellStdout) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResize) Reset() {
	*x = ShellResize{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResize) ProtoMessage() {}

func (x *ShellResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResize.ProtoReflect.Descriptor instead.
func (*ShellResize) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{12}
}

func (x *ShellResize) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellResize) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type ShellAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellAttach) Reset() {
	*x = ShellAttach{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellAttach) ProtoMessage() {}

func (x *ShellAttach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellAttach.ProtoReflect.Descriptor instead.
func (*ShellAttach) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{13}
}

func (x *ShellAttach) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

func (x *ShellAttach) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type ShellDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellDetach) Reset() {
	*x = ShellDetach{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellDetach) ProtoMessage() {}

func (x *ShellDetach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellDetach.ProtoReflect.Descriptor instead.
func (*ShellDetach) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{14}
}

func (x *ShellDetach) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       int32                  `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{15}
}

func (x *TerminalSize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type ShellTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellTypes) Reset() {
	*x = ShellTypes{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellTypes) ProtoMessage() {}

func (x *ShellTypes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellTypes.ProtoReflect.Descriptor instead.
func (*ShellTypes) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{16}
}

func (x *ShellTypes) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ShellSessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ShellSession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellSessions) Reset() {
	*x = ShellSessions{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellSessions) ProtoMessage() {}

func (x *ShellSessions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellSessions.ProtoReflect.Descriptor instead.
func (*ShellSessions) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{17}
}

func (x *ShellSessions) GetSessions() []*ShellSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ShellSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsAttached    bool                   `protobuf:"varint,3,opt,name=is_attached,json=isAttached,proto3" json:"is_attached,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellSession) Reset() {
	*x = ShellSession{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellSession) ProtoMessage() {}

func (x *ShellSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellSession.ProtoReflect.Descriptor instead.
func (*ShellSession) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{18}
}

func (x *ShellSession) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShellSession) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShellSession) GetIsAttached() bool {
	if x != nil {
		return x.IsAttached
	}
	return false
}

func (x *ShellSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ShellCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCreate) Reset() {
	*x = ShellCreate{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCreate) ProtoMessage() {}

func (x *ShellCreate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCreate.ProtoReflect.Descriptor instead.
func (*ShellCreate) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{19}
}

func (x *ShellCreate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShellCreate) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ShellCreate) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type ShellDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellDump) Reset() {
	*x = ShellDump{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellDump) ProtoMessage() {}

func (x *ShellDump) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellDump.ProtoReflect.Descriptor instead.
func (*ShellDump) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{20}
}

func (x *ShellDump) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

type ShellDumpData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ShellSession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellDumpData) Reset() {
	*x = ShellDumpData{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellDumpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellDumpData) ProtoMessage() {}

func (x *ShellDumpData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellDumpData.ProtoReflect.Descriptor instead.
func (*ShellDumpData) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{21}
}

func (x *ShellDumpData) GetSession() *ShellSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ShellDumpData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellKill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShellId       uint64                 `protobuf:"varint,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellKill) Reset() {
	*x = ShellKill{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellKill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellKill) ProtoMessage() {}

func (x *ShellKill) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellKill.ProtoReflect.Descriptor instead.
func (*ShellKill) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{22}
}

func (x *ShellKill) GetShellId() uint64 {
	if x != nil {
		return x.ShellId
	}
	return 0
}

type ListShellTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShellTypes) Reset() {
	*x = ListShellTypes{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShellTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShellTypes) ProtoMessage() {}

func (x *ListShellTypes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShellTypes.ProtoReflect.Descriptor instead.
func (*ListShellTypes) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{23}
}

type ListShellSessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShellSessions) Reset() {
	*x = ListShellSessions{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShellSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShellSessions) ProtoMessage() {}

func (x *ListShellSessions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShellSessions.ProtoReflect.Descriptor instead.
func (*ListShellSessions) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{24}
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{25}
}

func (x *TransferRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type TransferChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*TransferChunk_Metadata
	//	*TransferChunk_Data
	Chunk         isTransferChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferChunk) Reset() {
	*x = TransferChunk{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferChunk) ProtoMessage() {}

func (x *TransferChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferChunk.ProtoReflect.Descriptor instead.
func (*TransferChunk) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{26}
}

func (x *TransferChunk) GetChunk() isTransferChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *TransferChunk) GetMetadata() *TransferMetadata {
	if x != nil {
		if x, ok := x.Chunk.(*TransferChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *TransferChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*TransferChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isTransferChunk_Chunk interface {
	isTransferChunk_Chunk()
}

type TransferChunk_Metadata struct {
	Metadata *TransferMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type TransferChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*TransferChunk_Metadata) isTransferChunk_Chunk() {}

func (*TransferChunk_Data) isTransferChunk_Chunk() {}

type TransferMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMetadata) Reset() {
	*x = TransferMetadata{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMetadata) ProtoMessage() {}

func (x *TransferMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMetadata.ProtoReflect.Descriptor instead.
func (*TransferMetadata) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{27}
}

func (x *TransferMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TransferMetadata) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TransferMetadata) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *TransferMetadata) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TransferResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Path             string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	BytesTransferred uint64                 `protobuf:"varint,4,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResult.ProtoReflect.Descriptor instead.
func (*TransferResult) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{28}
}

func (x *TransferResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TransferResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TransferResult) GetBytesTransferred() uint64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shared_proto_gonduit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_shared_proto_gonduit_proto_rawDescGZIP(), []int{29}
}

var File_internal_shared_proto_gonduit_proto protoreflect.FileDescriptor

const file_internal_shared_proto_gonduit_proto_rawDesc = "" +
	"\n" +
	"#internal/shared/proto/gonduit.proto\x12\agonduit\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\fHelloRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"\x82\x01\n" +
	"\rHelloResponse\x12.\n" +
	"\thost_info\x18\x01 \x01(\v2\x11.gonduit.HostInfoR\bhostInfo\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"\xda\x01\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x05 \x01(\tR\x04port\x12'\n" +
	"\x0fnetwork_adapter\x18\x06 \x01(\tR\x0enetworkAdapter\x12(\n" +
	"\aos_info\x18\a \x01(\v2\x0f.gonduit.OSInfoR\x06osInfo\"x\n" +
	"\x06OSInfo\x12\x16\n" +
	"\x06Family\x18\x01 \x01(\tR\x06Family\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\tR\aVersion\x12\x14\n" +
	"\x05Build\x18\x04 \x01(\tR\x05Build\x12\x12\n" +
	"\x04Arch\x18\x05 \x01(\tR\x04Arch\"\xed\x03\n" +
	"\x12ShellClientMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\n" +
	"list_types\x18\x02 \x01(\v2\x17.gonduit.ListShellTypesH\x00R\tlistTypes\x12A\n" +
	"\rlist_sessions\x18\x03 \x01(\v2\x1a.gonduit.ListShellSessionsH\x00R\flistSessions\x12.\n" +
	"\x06create\x18\x04 \x01(\v2\x14.gonduit.ShellCreateH\x00R\x06create\x12(\n" +
	"\x04kill\x18\x05 \x01(\v2\x12.gonduit.ShellKillH\x00R\x04kill\x12+\n" +
	"\x05stdin\x18\x06 \x01(\v2\x13.gonduit.ShellStdinH\x00R\x05stdin\x12.\n" +
	"\x06resize\x18\a \x01(\v2\x14.gonduit.ShellResizeH\x00R\x06resize\x12.\n" +
	"\x06attach\x18\b \x01(\v2\x14.gonduit.ShellAttachH\x00R\x06attach\x12.\n" +
	"\x06detach\x18\t \x01(\v2\x14.gonduit.ShellDetachH\x00R\x06detach\x12(\n" +
	"\x04dump\x18\n" +
	" \x01(\v2\x12.gonduit.ShellDumpH\x00R\x04dumpB\t\n" +
	"\amessage\"\xa7\x03\n" +
	"\x12ShellServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x02ok\x18\x02 \x01(\v2\x10.gonduit.ShellOkH\x00R\x02ok\x12.\n" +
	"\x06stdout\x18\x03 \x01(\v2\x14.gonduit.ShellStdoutH\x00R\x06stdout\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.gonduit.ShellErrorH\x00R\x05error\x12.\n" +
	"\x06exited\x18\x05 \x01(\v2\x14.gonduit.ShellExitedH\x00R\x06exited\x12+\n" +
	"\x05types\x18\x06 \x01(\v2\x13.gonduit.ShellTypesH\x00R\x05types\x124\n" +
	"\bsessions\x18\a \x01(\v2\x16.gonduit.ShellSessionsH\x00R\bsessions\x124\n" +
	"\battached\x18\b \x01(\v2\x16.gonduit.ShellAttachedH\x00R\battached\x12,\n" +
	"\x04dump\x18\t \x01(\v2\x16.gonduit.ShellDumpDataH\x00R\x04dumpB\t\n" +
	"\amessage\"$\n" +
	"\aShellOk\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\"]\n" +
	"\vShellExited\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"=\n" +
	"\n" +
	"ShellError\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\";\n" +
	"\n" +
	"ShellStdin\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\">\n" +
	"\rShellAttached\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"<\n" +
	"\vShellStdout\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"S\n" +
	"\vShellResize\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12)\n" +
	"\x04size\x18\x02 \x01(\v2\x15.gonduit.TerminalSizeR\x04size\"S\n" +
	"\vShellAttach\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\x12)\n" +
	"\x04size\x18\x02 \x01(\v2\x15.gonduit.TerminalSizeR\x04size\"(\n" +
	"\vShellDetach\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\"<\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\x05R\acolumns\"\"\n" +
	"\n" +
	"ShellTypes\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"B\n" +
	"\rShellSessions\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.gonduit.ShellSessionR\bsessions\"\x8e\x01\n" +
	"\fShellSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vis_attached\x18\x03 \x01(\bR\n" +
	"isAttached\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"`\n" +
	"\vShellCreate\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12)\n" +
	"\x04size\x18\x03 \x01(\v2\x15.gonduit.TerminalSizeR\x04size\"&\n" +
	"\tShellDump\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\"T\n" +
	"\rShellDumpData\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.gonduit.ShellSessionR\asession\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"&\n" +
	"\tShellKill\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\x04R\ashellId\"\x10\n" +
	"\x0eListShellTypes\"\x13\n" +
	"\x11ListShellSessions\"%\n" +
	"\x0fTransferRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"g\n" +
	"\rTransferChunk\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.gonduit.TransferMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05chunk\"t\n" +
	"\x10TransferMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\x81\x01\n" +
	"\x0eTransferResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12+\n" +
	"\x11bytes_transferred\x18\x04 \x01(\x04R\x10bytesTransferred\"\a\n" +
	"\x05Empty2\x9a\x02\n" +
	"\x0eGonduitService\x126\n" +
	"\x05Hello\x12\x15.gonduit.HelloRequest\x1a\x16.gonduit.HelloResponse\x12K\n" +
	"\vShellStream\x12\x1b.gonduit.ShellClientMessage\x1a\x1b.gonduit.ShellServerMessage(\x010\x01\x12?\n" +
	"\n" +
	"UploadFile\x12\x16.gonduit.TransferChunk\x1a\x17.gonduit.TransferResult(\x01\x12B\n" +
	"\fDownloadFile\x12\x18.gonduit.TransferRequest\x1a\x16.gonduit.TransferChunk0\x01B\x0eZ\fshared/protob\x06proto3"

var (
	file_internal_shared_proto_gonduit_proto_rawDescOnce sync.Once
	file_internal_shared_proto_gonduit_proto_rawDescData []byte
)

func file_internal_shared_proto_gonduit_proto_rawDescGZIP() []byte {
	file_internal_shared_proto_gonduit_proto_rawDescOnce.Do(func() {
		file_internal_shared_proto_gonduit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_shared_proto_gonduit_proto_rawDesc), len(file_internal_shared_proto_gonduit_proto_rawDesc)))
	})
	return file_internal_shared_proto_gonduit_proto_rawDescData
}

var file_internal_shared_proto_gonduit_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_internal_shared_proto_gonduit_proto_goTypes = []any{
	(*HelloRequest)(nil),          // 0: gonduit.HelloRequest
	(*HelloResponse)(nil),         // 1: gonduit.HelloResponse
	(*HostInfo)(nil),              // 2: gonduit.HostInfo
	(*OSInfo)(nil),                // 3: gonduit.OSInfo
	(*ShellClientMessage)(nil),    // 4: gonduit.ShellClientMessage
	(*ShellServerMessage)(nil),    // 5: gonduit.ShellServerMessage
	(*ShellOk)(nil),               // 6: gonduit.ShellOk
	(*ShellExited)(nil),           // 7: gonduit.ShellExited
	(*ShellError)(nil),            // 8: gonduit.ShellError
	(*ShellStdin)(nil),            // 9: gonduit.ShellStdin
	(*ShellAttached)(nil),         // 10: gonduit.ShellAttached
	(*ShellStdout)(nil),           // 11: gonduit.ShellStdout
	(*ShellResize)(nil),           // 12: gonduit.ShellResize
	(*ShellAttach)(nil),           // 13: gonduit.ShellAttach
	(*ShellDetach)(nil),           // 14: gonduit.ShellDetach
	(*TerminalSize)(nil),          // 15: gonduit.TerminalSize
	(*ShellTypes)(nil),            // 16: gonduit.ShellTypes
	(*ShellSessions)(nil),         // 17: gonduit.ShellSessions
	(*ShellSession)(nil),          // 18: gonduit.ShellSession
	(*ShellCreate)(nil),           // 19: gonduit.ShellCreate
	(*ShellDump)(nil),             // 20: gonduit.ShellDump
	(*ShellDumpData)(nil),         // 21: gonduit.ShellDumpData
	(*ShellKill)(nil),             // 22: gonduit.ShellKill
	(*ListShellTypes)(nil),        // 23: gonduit.ListShellTypes
	(*ListShellSessions)(nil),     // 24: gonduit.ListShellSessions
	(*TransferRequest)(nil),       // 25: gonduit.TransferRequest
	(*TransferChunk)(nil),         // 26: gonduit.TransferChunk
	(*TransferMetadata)(nil),      // 27: gonduit.TransferMetadata
	(*TransferResult)(nil),        // 28: gonduit.TransferResult
	(*Empty)(nil),                 // 29: gonduit.Empty
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_internal_shared_proto_gonduit_proto_depIdxs = []int32{
	2,  // 0: gonduit.HelloResponse.host_info:type_name -> gonduit.HostInfo
	3,  // 1: gonduit.HostInfo.os_info:type_name -> gonduit.OSInfo
	23, // 2: gonduit.ShellClientMessage.list_types:type_name -> gonduit.ListShellTypes
	24, // 3: gonduit.ShellClientMessage.list_sessions:type_name -> gonduit.ListShellSessions
	19, // 4: gonduit.ShellClientMessage.create:type_name -> gonduit.ShellCreate
	22, // 5: gonduit.ShellClientMessage.kill:type_name -> gonduit.ShellKill
	9,  // 6: gonduit.ShellClientMessage.stdin:type_name -> gonduit.ShellStdin
	12, // 7: gonduit.ShellClientMessage.resize:type_name -> gonduit.ShellResize
	13, // 8: gonduit.ShellClientMessage.attach:type_name -> gonduit.ShellAttach
	14, // 9: gonduit.ShellClientMessage.detach:type_name -> gonduit.ShellDetach
	20, // 10: gonduit.ShellClientMessage.dump:type_name -> gonduit.ShellDump
	6,  // 11: gonduit.ShellServerMessage.ok:type_name -> gonduit.ShellOk
	11, // 12: gonduit.ShellServerMessage.stdout:type_name -> gonduit.ShellStdout
	8,  // 13: gonduit.ShellServerMessage.error:type_name -> gonduit.ShellError
	7,  // 14: gonduit.ShellServerMessage.exited:type_name -> gonduit.ShellExited
	16, // 15: gonduit.ShellServerMessage.types:type_name -> gonduit.ShellTypes
	17, // 16: gonduit.ShellServerMessage.sessions:type_name -> gonduit.ShellSessions
	10, // 17: gonduit.ShellServerMessage.attached:type_name -> gonduit.ShellAttached
	21, // 18: gonduit.ShellServerMessage.dump:type_name -> gonduit.ShellDumpData
	15, // 19: gonduit.ShellResize.size:type_name -> gonduit.TerminalSize
	15, // 20: gonduit.ShellAttach.size:type_name -> gonduit.TerminalSize
	18, // 21: gonduit.ShellSessions.sessions:type_name -> gonduit.ShellSession
	30, // 22: gonduit.ShellSession.created_at:type_name -> google.protobuf.Timestamp
	15, // 23: gonduit.ShellCreate.size:type_name -> gonduit.TerminalSize
	18, // 24: gonduit.ShellDumpData.session:type_name -> gonduit.ShellSession
	27, // 25: gonduit.TransferChunk.metadata:type_name -> gonduit.TransferMetadata
	0,  // 26: gonduit.GonduitService.Hello:input_type -> gonduit.HelloRequest
	4,  // 27: gonduit.GonduitService.ShellStream:input_type -> gonduit.ShellClientMessage
	26, // 28: gonduit.GonduitService.UploadFile:input_type -> gonduit.TransferChunk
	25, // 29: gonduit.GonduitService.DownloadFile:input_type -> gonduit.TransferRequest
	1,  // 30: gonduit.GonduitService.Hello:output_type -> gonduit.HelloResponse
	5,  // 31: gonduit.GonduitService.ShellStream:output_type -> gonduit.ShellServerMessage
	28, // 32: gonduit.GonduitService.UploadFile:output_type -> gonduit.TransferResult
	26, // 33: gonduit.GonduitService.DownloadFile:output_type -> gonduit.TransferChunk
	30, // [30:34] is the sub-list for method output_type
	26, // [26:30] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_internal_shared_proto_gonduit_proto_init() }
func file_internal_shared_proto_gonduit_proto_init() {
	if File_internal_shared_proto_gonduit_proto != nil {
		return
	}
	file_internal_shared_proto_gonduit_proto_msgTypes[4].OneofWrappers = []any{
		(*ShellClientMessage_ListTypes)(nil),
		(*ShellClientMessage_ListSessions)(nil),
		(*ShellClientMessage_Create)(nil),
		(*ShellClientMessage_Kill)(nil),
		(*ShellClientMessage_Stdin)(nil),
		(*ShellClientMessage_Resize)(nil),
		(*ShellClientMessage_Attach)(nil),
		(*ShellClientMessage_Detach)(nil),
		(*ShellClientMessage_Dump)(nil),
	}
	file_internal_shared_proto_gonduit_proto_msgTypes[5].OneofWrappers = []any{
		(*ShellServerMessage_Ok)(nil),
		(*ShellServerMessage_Stdout)(nil),
		(*ShellServerMessage_Error)(nil),
		(*ShellServerMessage_Exited)(nil),
		(*ShellServerMessage_Types)(nil),
		(*ShellServerMessage_Sessions)(nil),
		(*ShellServerMessage_Attached)(nil),
		(*ShellServerMessage_Dump)(nil),
	}
	file_internal_shared_proto_gonduit_proto_msgTypes[26].OneofWrappers = []any{
		(*TransferChunk_Metadata)(nil),
		(*TransferChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_shared_proto_gonduit_proto_rawDesc), len(file_internal_shared_proto_gonduit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_shared_proto_gonduit_proto_goTypes,
		DependencyIndexes: file_internal_shared_proto_gonduit_proto_depIdxs,
		MessageInfos:      file_internal_shared_proto_gonduit_proto_msgTypes,
	}.Build()
	File_internal_shared_proto_gonduit_proto = out.File
	file_internal_shared_proto_gonduit_proto_goTypes = nil
	file_internal_shared_proto_gonduit_proto_depIdxs = nil
}
