// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: internal/shared/proto/gonduit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GonduitService_Hello_FullMethodName        = "/gonduit.GonduitService/Hello"
	GonduitService_ShellStream_FullMethodName  = "/gonduit.GonduitService/ShellStream"
	GonduitService_UploadFile_FullMethodName   = "/gonduit.GonduitService/UploadFile"
	GonduitService_DownloadFile_FullMethodName = "/gonduit.GonduitService/DownloadFile"
)

// GonduitServiceClient is the client API for GonduitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GonduitServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	ShellStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellClientMessage, ShellServerMessage], error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TransferChunk, TransferResult], error)
	DownloadFile(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferChunk], error)
}

type gonduitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGonduitServiceClient(cc grpc.ClientConnInterface) GonduitServiceClient {
	return &gonduitServiceClient{cc}
}

func (c *gonduitServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GonduitService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gonduitServiceClient) ShellStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellClientMessage, ShellServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GonduitService_ServiceDesc.Streams[0], GonduitService_ShellStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellClientMessage, ShellServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonduitService_ShellStreamClient = grpc.BidiStreamingClient[ShellClientMessage, ShellServerMessage]

func (c *gonduitServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TransferChunk, TransferResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GonduitService_ServiceDesc.Streams[1], GonduitService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferChunk, TransferResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonduitService_UploadFileClient = grpc.ClientStreamingClient[TransferChunk, TransferResult]

func (c *gonduitServiceClient) DownloadFile(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GonduitService_ServiceDesc.Streams[2], GonduitService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferRequest, TransferChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonduitService_DownloadFileClient = grpc.ServerStreamingClient[TransferChunk]

// GonduitServiceServer is the server API for GonduitService service.
// All implementations must embed UnimplementedGonduitServiceServer
// for forward compatibility.
type GonduitServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	ShellStream(grpc.BidiStreamingServer[ShellClientMessage, ShellServerMessage]) error
	UploadFile(grpc.ClientStreamingServer[TransferChunk, TransferResult]) error
	DownloadFile(*TransferRequest, grpc.ServerStreamingServer[TransferChunk]) error
	mustEmbedUnimplementedGonduitServiceServer()
}

// UnimplementedGonduitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGonduitServiceServer struct{}

func (UnimplementedGonduitServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedGonduitServiceServer) ShellStream(grpc.BidiStreamingServer[ShellClientMessage, ShellServerMessage]) error {
	return status.Error(codes.Unimplemented, "method ShellStream not implemented")
}
func (UnimplementedGonduitServiceServer) UploadFile(grpc.ClientStreamingServer[TransferChunk, TransferResult]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedGonduitServiceServer) DownloadFile(*TransferRequest, grpc.ServerStreamingServer[TransferChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedGonduitServiceServer) mustEmbedUnimplementedGonduitServiceServer() {}
func (UnimplementedGonduitServiceServer) testEmbeddedByValue()                        {}

// UnsafeGonduitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GonduitServiceServer will
// result in compilation errors.
type UnsafeGonduitServiceServer interface {
	mustEmbedUnimplementedGonduitServiceServer()
}

func RegisterGonduitServiceServer(s grpc.ServiceRegistrar, srv GonduitServiceServer) {
	// If the following call panics, it indicates UnimplementedGonduitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GonduitService_ServiceDesc, srv)
}

func _GonduitService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GonduitServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GonduitService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GonduitServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GonduitService_ShellStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GonduitServiceServer).ShellStream(&grpc.GenericServerStream[ShellClientMessage, ShellServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonduitService_ShellStreamServer = grpc.BidiStreamingServer[ShellClientMessage, ShellServerMessage]

func _GonduitService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GonduitServiceServer).UploadFile(&grpc.GenericServerStream[TransferChunk, TransferResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonduitService_UploadFileServer = grpc.ClientStreamingServer[TransferChunk, TransferResult]

func _GonduitService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransferRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GonduitServiceServer).DownloadFile(m, &grpc.GenericServerStream[TransferRequest, TransferChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonduitService_DownloadFileServer = grpc.ServerStreamingServer[TransferChunk]

// GonduitService_ServiceDesc is the grpc.ServiceDesc for GonduitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GonduitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gonduit.GonduitService",
	HandlerType: (*GonduitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GonduitService_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ShellStream",
			Handler:       _GonduitService_ShellStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _GonduitService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _GonduitService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/shared/proto/gonduit.proto",
}
